config/routes.rb
Rails.application.routes.draw do
  resources :fights
  resources :fights
  get 'static_pages/home'
  post '/fights/challenger_pokemon', to: 'fights#challenger_pokemon', as: 'challenger_pokemon'
  post '/fights/challenged_player', to: 'fights#challenged_player', as: 'challenged_player'
  post '/fights/challenged_pokemon', to: 'fights#challenged_pokemon', as: 'challenged_pokemon'
  post '/fights/create_fight', to: 'fights#create_fight', as: 'create_fight'
  get 'static_pages/standings', to: 'static_pages#standings', as: 'standings'
  get 'pokemons/select_one' => 'pokemons#select_one', :as => 'select_one'
  get 'player_pokemons/createpk' => 'player_pokemons#createpk', :as => 'createpk'

  root 'static_pages#home'
  resources :player_pokemons
  resources :pokemons
  resources :players

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def standings
    @ch = Player.joins("INNER JOIN Fights ON Fights.challenger_player_id = Players.id ") 
    @cd = Player.joins("INNER JOIN Fights ON Fights.challenged_player_id = Players.id ") 
    @players =Player.order(win_count: :desc)
    
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Poke Fight</h1>
<p>
  This is the home page for PokeFight
</p>


<div class="col-sm-6 col-md-3">
	<div class="thumbnail tile tile-medium tile-green">
        <a href=<%= pokemons_path %> class="fa-links">
            <h1>All Pokemon</h1>
                <i class="fa fa-3x fa-home"></i>
		</a>
    </div>
</div>
<div class="col-sm-6 col-md-3">
	<div class="thumbnail tile tile-medium tile-orange">
        <a href= <%= players_path %> class="fa-links">
            <h1>All Players</h1>
                <i class="fa fa-3x fa-rss-square"></i>
		</a>
	</div>
</div>

<div class="col-sm-6 col-md-3">
	<div class="thumbnail tile tile-medium tile-green">
        <a href=<%=fights_path %> class="fa-links">
            <h1>All Fixtures</h1>
                <i class="fa fa-3x fa-home"></i>
		</a>
    </div>
</div>
<div class="col-sm-6 col-md-3">
	<div class="thumbnail tile tile-medium tile-orange">
        <a href= <%= standings_path %> class="fa-links">
            <h1>Standings</h1>
                <i class="fa fa-3x fa-rss-square"></i>
		</a>
	</div>
</div>

app/views/static_pages/standings.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players according to Rank</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Win count</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td class="abc"><%= player.name %></td>
        <td class="abc"><%= player.city %></td>
        <td class="abc"><%= player.win_count %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <!--<td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Player', new_player_path %>-->