config/routes.rb
Rails.application.routes.draw do
  resources :fights
  resources :fights
  get 'static_pages/home'
  post '/fights/challenger_pokemon', to: 'fights#challenger_pokemon', as: 'challenger_pokemon'
  post '/fights/challenged_player', to: 'fights#challenged_player', as: 'challenged_player'
  post '/fights/challenged_pokemon', to: 'fights#challenged_pokemon', as: 'challenged_pokemon'
  post '/fights/create_fight', to: 'fights#create_fight', as: 'create_fight'
  get 'static_pages/standings', to: 'static_pages#standings', as: 'standings'
  get 'pokemons/select_one' => 'pokemons#select_one', :as => 'select_one'
  get 'player_pokemons/createpk' => 'player_pokemons#createpk', :as => 'createpk'

  root 'static_pages#home'
  resources :player_pokemons
  resources :pokemons
  resources :players

end

app/models/player.rb
class Player < ActiveRecord::Base
  before_save :default_values
  def default_values
    if self.win_count != nil and self.win_count <0 then
      self.win_count = 0
    end
    self.win_count ||= 0
  end

  has_many :player_pokemons, :dependent => :destroy
  has_many :pokemons, -> { uniq }, :through => :player_pokemons
  has_many :fights
  validates :name, presence: { message: "Player Name is required" }, uniqueness: {message: "This name is already taken." }
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
    id = params[:id] # retrieve player ID from URI route
    @player = Player.find(id) # look up player by unique ID
    @pokemons = @player.pokemons
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :city, :win_count)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <!--<div class="field">-->
    <!--<%= f.label :win_count %>-->
    <br>
    <!--<%= f.number_field :win_count, min:0 %>-->
  <!--</div>-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Win count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td class="abc"><%= player.name %></td>
        <td class="abc"><%= player.city %></td>
        <td class="abc"><%= player.win_count %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @player.city %>
</p>

<p>
  <strong>Win count:</strong>
  <%= @player.win_count %>
</p>
<p>
<strong><%= @player.name %>'s Pokemons: </strong>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dex number</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @player.pokemons.each do |pokemon| %>
      <tr>
        <td><%= pokemon.name %></td>
        <td><%= pokemon.dex_number %></td>
        <td><img alt= <%= pokemon.name%> src= <%=pokemon.image%> width="50" height="50" /></td> 
        <td><%= link_to 'Show', pokemon %></td>
      </tr>
    <% end %>
  </tbody>
</table>


</p>


<%= link_to 'Add Pokemons', select_one_path(:player_id => @player.id) %> |
<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>