config/routes.rb
Rails.application.routes.draw do
  resources :fights
  resources :fights
  get 'static_pages/home'
  post '/fights/challenger_pokemon', to: 'fights#challenger_pokemon', as: 'challenger_pokemon'
  post '/fights/challenged_player', to: 'fights#challenged_player', as: 'challenged_player'
  post '/fights/challenged_pokemon', to: 'fights#challenged_pokemon', as: 'challenged_pokemon'
  post '/fights/create_fight', to: 'fights#create_fight', as: 'create_fight'
  get 'static_pages/standings', to: 'static_pages#standings', as: 'standings'
  get 'pokemons/select_one' => 'pokemons#select_one', :as => 'select_one'
  get 'player_pokemons/createpk' => 'player_pokemons#createpk', :as => 'createpk'

  root 'static_pages#home'
  resources :player_pokemons
  resources :pokemons
  resources :players

end

app/models/player_pokemon.rb
class PlayerPokemon < ActiveRecord::Base
  belongs_to :player
  belongs_to :pokemon
  
  validates :player_id, presence: { message: "Player Name is required" }, uniqueness: { scope: :pokemon_id, message:" already has this pokemon." }
end

app/controllers/player_pokemons_controller.rb
class PlayerPokemonsController < ApplicationController
  before_action :set_player_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /player_pokemons
  # GET /player_pokemons.json
  def index
     
    @player_pokemons = PlayerPokemon.all
  end

  # GET /player_pokemons/1
  # GET /player_pokemons/1.json
  def show
  end

  # GET /player_pokemons/new
  def new
    @player_pokemon = PlayerPokemon.new
  end

  # GET /player_pokemons/1/edit
  def edit
  end

  # POST /player_pokemons
  # POST /player_pokemons.json
  def createpk
    @player_pokemon = PlayerPokemon.new(player_pokemon_params)

    respond_to do |format|
      if @player_pokemon.save
        format.html { redirect_to @player_pokemon, notice: 'Pokemon was successfully captured.' }
        format.json { render :show, status: :created, location: @player_pokemon }
      else
        format.html { render :new }
        format.json { render json: @player_pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_pokemons/1
  # PATCH/PUT /player_pokemons/1.json
  def update
    respond_to do |format|
      if @player_pokemon.update(player_pokemon_params)
        format.html { redirect_to @player_pokemon, notice: 'Player pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @player_pokemon }
      else
        format.html { render :edit }
        format.json { render json: @player_pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_pokemons/1
  # DELETE /player_pokemons/1.json
  def destroy
    @player_pokemon.destroy
    respond_to do |format|
      format.html { redirect_to player_pokemons_url, notice: 'Pokemon was successfully removed from the player.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_pokemon
      @player_pokemon = PlayerPokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_pokemon_params
      params.permit(:player_id, :pokemon_id)
    end
end

app/helpers/player_pokemons_helper.rb
module PlayerPokemonsHelper
end

app/views/player_pokemons/_form.html.erb
<%= form_for(@player_pokemon) do |f| %>
  <% if @player_pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player_pokemon.errors.count, "error") %> prohibited this player_pokemon from being saved:</h2>

      <ul>
      <% @player_pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.number_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :pokemon_id %><br>
    <%= f.number_field :pokemon_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/player_pokemons/edit.html.erb
<h1>Editing Player Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show', @player_pokemon %> |
<%= link_to 'Back', player_pokemons_path %>

app/views/player_pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Player Pokemons</h1>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Pokemon</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @player_pokemons.each do |player_pokemon| %>
      <tr>
        <td><%= Player.find(player_pokemon.player_id).name %></td>
        <td><%= Pokemon.find(player_pokemon.pokemon_id).name %></td>
        <td><%= link_to 'Show', player_pokemon %></td>
        <!--<td><%= link_to 'Edit', edit_player_pokemon_path(player_pokemon) %></td>-->
        <td><%= link_to 'Destroy', player_pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Player pokemon', new_player_pokemon_path %>-->

app/views/player_pokemons/new.html.erb
<h1>New Player Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Back', player_pokemons_path %>

app/views/player_pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= Player.find(@player_pokemon.player_id).name %>
</p>

<p>
  <strong>Pokemon:</strong>
  <%= Pokemon.find(@player_pokemon.pokemon_id).name %>
</p>

<!--<%= link_to 'Edit', edit_player_pokemon_path(@player_pokemon) %> |-->
<%= link_to 'Back', player_pokemons_path %>