config/routes.rb
Rails.application.routes.draw do
  resources :fights
  resources :fights
  get 'static_pages/home'
  post '/fights/challenger_pokemon', to: 'fights#challenger_pokemon', as: 'challenger_pokemon'
  post '/fights/challenged_player', to: 'fights#challenged_player', as: 'challenged_player'
  post '/fights/challenged_pokemon', to: 'fights#challenged_pokemon', as: 'challenged_pokemon'
  post '/fights/create_fight', to: 'fights#create_fight', as: 'create_fight'
  get 'static_pages/standings', to: 'static_pages#standings', as: 'standings'
  get 'pokemons/select_one' => 'pokemons#select_one', :as => 'select_one'
  get 'player_pokemons/createpk' => 'player_pokemons#createpk', :as => 'createpk'

  root 'static_pages#home'
  resources :player_pokemons
  resources :pokemons
  resources :players

end

app/models/fight.rb
class Fight < ActiveRecord::Base
    has_many :players
    validates :challenger_player_id, presence: true
    validates :challenger_pokemon_id, presence: true
    validates :challenged_player_id, presence: true
    validates :challenged_pokemon_id, presence: true
    validates :fight_date, presence: true
    validates :fight_winner, presence: true
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  before_action :set_fight, only: [:show, :edit, :update, :destroy]

  # GET /fights
  # GET /fights.json
  def index
    @fights = Fight.all
  end

  # GET /fights/1
  # GET /fights/1.json
  def show
  end

  # GET /fights/new
  def new
    @fight = Fight.new
    @players =Player.joins(:player_pokemons).distinct
  end

  # GET /fights/1/edit
  def edit
  end
  
  
  def challenger_pokemon
    @player1 = params[:challenger][:challenger_player_id]
    @pokemons = Player.find(params[:challenger][:challenger_player_id]).pokemons
  end


  def challenged_player
    @players =Player.joins(:player_pokemons).distinct

    @players2 = @players.where.not(id: params[:player1_id])
   
    @player1 = params[:player1_id]
    @pokemon1 = params[:pokemon][:challenger_pokemon_id]
    # params[:player1_id] = params[:players1_id]
    # params[:pokemon1_id] = params[:pokemon][:challenger_pokemon_id]
  end
  
  def challenged_pokemon
    @player1 = params[:player1_id]
    @pokemon1 = params[:pokemon1_id]
    @player2 = params[:challenged][:challenged_player_id]
    
    @pokemons = Player.find(@player2).pokemons

    # params[:player1_id] = params[:players1_id]
    # params[:pokemon1_id] = params[:pokemon][:challenger_pokemon_id]
  end
  
  def create_fight
    @player1 = params[:player1_id]
    @pokemon1 = params[:pokemon1_id]
    @player2 = params[:player2_id]
    @pokemon2= params[:pokemon2][:challenged_pokemon_id]
    @fight = Fight.new
    @winner = [@player1,@player2]; 
    # params[:player1_id] = params[:players1_id]
    # params[:pokemon1_id] = params[:pokemon][:challenger_pokemon_id]
  end
  
  
  
  # POST /fights
  # POST /fights.json
  def create
    params[:fight_date] = params[:fight][:fight_date]
    @fight = Fight.new(fight_params)

    respond_to do |format|
      if @fight.save
        p = Player.find(params[:fight_winner])
        p.increment!(:win_count)
        format.html { redirect_to @fight, notice: 'Fight was successfully created.' }
        format.json { render :show, status: :created, location: @fight }
      else
        format.html { render :new }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fights/1
  # PATCH/PUT /fights/1.json
  def update
    respond_to do |format|
      if @fight.update(fight_params)
        format.html { redirect_to @fight, notice: 'Fight was successfully updated.' }
        format.json { render :show, status: :ok, location: @fight }
      else
        format.html { render :edit }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fights/1
  # DELETE /fights/1.json
  def destroy
    p = Player.find(@fight.fight_winner)
    @fight.destroy
    p.decrement!(:win_count)
    respond_to do |format|
      format.html { redirect_to fights_url, notice: 'Fight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fight
      @fight = Fight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fight_params
      params.permit(:challenger_player_id, :challenger_pokemon_id, :challenged_player_id, :challenged_pokemon_id, :fight_date, :fight_winner)
    end
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/views/fights/_form.html.erb
<%= form_for(@fight) do |f| %>
  <!--<% if @fight.errors.any? %>-->
  <!--  <div id="error_explanation">-->
  <!--    <h2><%= pluralize(@fight.errors.count, "error") %> prohibited this fight from being saved:</h2>-->

  <!--    <ul>-->
  <!--    <% @fight.errors.full_messages.each do |message| %>-->
  <!--      <li><%= message %></li>-->
  <!--    <% end %>-->
  <!--    </ul>-->
  <!--  </div>-->
  <!--<% end %>-->

  <div class="field">
    <%= f.label :challenger_player_id %><br>
    <%= f.collection_select(:challenger_player_id, @players, :id, :name) %>
    <!--<%= f.text_field :challenger_player_id %>-->
  </div>
  <!--<div class="field">-->
  <!--  <%= f.label :challenger_pokemon_id %><br>-->
  <!--  <%= f.text_field :challenger_pokemon_id %>-->
  <!--</div>-->
  <!--<div class="field">-->
  <!--  <%= f.label :challenged_player_id %><br>-->
  <!--  <%= f.text_field :challenged_player_id %>-->
  <!--</div>-->
  <!--<div class="field">-->
  <!--  <%= f.label :challenged_pokemon_id %><br>-->
  <!--  <%= f.text_field :challenged_pokemon_id %>-->
  <!--</div>-->
  <div class="field">
    <%= f.label :fight_date %><br>
    <%= f.date_field    :fight_date %>
  </div>
  <!--<div class="field">-->
  <!--  <%= f.label :fight_winner %><br>-->
  <!--  <%= f.number_field :fight_winner %>-->
  <!--</div>-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fights/challenged_player.html.erb
<%= form_for :challenged, url: challenged_pokemon_path(:player1_id => @player1, :pokemon1_id => @pokemon1) do |f| %>

   <div class="field">
    <%= f.label :challenged_player_id %><br>
    <%= f.collection_select(:challenged_player_id, @players2, :id, :name) %>
  </div>
  
  <%= f.submit  %>
<% end  %>


Challenger Player Name: <%=Player.find(@player1).name  %> 
<br>
Challenger Pokemon Name: <%=Pokemon.find(@pokemon1).name  %>

app/views/fights/challenged_pokemon.html.erb
<%= form_for :pokemon2, url: create_fight_path(:player1_id => @player1, :pokemon1_id => @pokemon1, :player2_id => @player2) do |f| %>
Choose one of the Pokemons of:   <%=Player.find(@player2).name  %> 
   <div class="field">
    <%= f.label :challenged_pokemon_id %><br>
    <%= f.collection_select(:challenged_pokemon_id, @pokemons, :id, :name) %>
  </div>
  
  <%= f.submit  %>
<% end  %>


Challenger Player Name: <%=Player.find(@player1).name  %> 
<br>
Challenger Pokemon Name: <%=Pokemon.find(@pokemon1).name  %>

app/views/fights/challenger_pokemon.html.erb
<%= form_for :pokemon, url: challenged_player_path(:player1_id => @player1) do |f| %>

   <div class="field">
    <%= f.label :challenger_pokemon_id %><br>
    <%= f.collection_select(:challenger_pokemon_id, @pokemons, :id, :name) %>
  </div>
  
  <%= f.submit  %>
<% end  %>

Challenger Player Name: <%=Player.find(params[:player1_id] = @player1).name  %> 

app/views/fights/create_fight.html.erb
<%= form_for :fight, url: fights_path(:challenger_player_id => @player1, :challenger_pokemon_id => @pokemon1, :challenged_player_id => @player2, :challenged_pokemon_id => @pokemon2 )  do |f| %>
  <% if @fight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fight.errors.count, "error") %> prohibited this fight from being saved:</h2>

      <ul>
      <% @fight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
Enter Fight Date, and Select the fight winner
  <div class="field">
     Challenger Player Name <br>
    <%= Player.find(@player1).name %>
    <!--<%= f.text_field :challenger_player_id %>-->
  </div>
  <div class="field">
    Challenger Pokemon Name <br>
    <%= Pokemon.find(@pokemon1).name %>
  </div>
  <div class="field">
    Challenged Player Name <br>
    <%= Player.find(@player2).name %>
  </div>
  <div class="field">
    Challenged Pokemon Name<br>
    <%= Pokemon.find(@pokemon2).name %>
  </div>
  <div class="field">
    <%= f.label :fight_date %><br>
    <%= f.date_field    :fight_date, :required => 'required'  %>
  </div>
  <div class="field">
    <%= f.label :fight_winner %><br>
    <%= select_tag(:fight_winner, options_for_select( [ [Player.find(@player1).name,@player1] ,[Player.find(@player2).name,@player2 ] ]) ) %>  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fights/edit.html.erb
<h1>Editing Fight</h1>

<%= render 'form' %>

<%= link_to 'Show', @fight %> |
<%= link_to 'Back', fights_path %>

app/views/fights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fights</h1>

<table>
  <thead>
    <tr>
      <th>Challenger player</th>
      <th>Challenger pokemon</th>
      <th>Challenged player</th>
      <th>Challenged pokemon</th>
      <th>Fight date</th>
      <th>Fight winner</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @fights.each do |fight| %>
      <tr>
        <td><%= Player.find(fight.challenger_player_id).name %></td>
        <td><%= Pokemon.find(fight.challenger_pokemon_id).name %></td>
        <td><%= Player.find(fight.challenged_player_id).name %></td>
        <td><%= Pokemon.find(fight.challenged_pokemon_id).name %></td>
        <td><%= fight.fight_date %></td>
        <td><%= Player.find(fight.fight_winner).name %></td>
        <td><%= link_to 'Show', fight %></td>
        <!--<td><%= link_to 'Edit', edit_fight_path(fight) %></td>-->
        <td><%= link_to 'Destroy', fight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fight', new_fight_path %>

app/views/fights/new.html.erb
<h1>New Fight</h1>

<%= form_for :challenger, url: challenger_pokemon_path do |f| %>

   <div class="field">
    <%= f.label :challenger_player_id %><br>
    <%= f.collection_select(:challenger_player_id, @players, :id, :name) %>
    <!--<%= f.text_field :challenger_player_id %>-->
  </div>
  
  <%= f.submit  %>
<% end  %>




<%= link_to 'Back', fights_path %>

app/views/fights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Challenger player:</strong>
  <%= Player.find(@fight.challenger_player_id).name %>
</p>

<p>
  <strong>Challenger pokemon:</strong>
  <%= Pokemon.find(@fight.challenger_pokemon_id).name %>
</p>

<p>
  <strong>Challenged player:</strong>
  <%= Player.find(@fight.challenged_player_id).name %>
</p>

<p>
  <strong>Challenged pokemon:</strong>
  <%= Pokemon.find(@fight.challenged_pokemon_id).name %>
</p>

<p>
  <strong>Fight date:</strong>
  <%= @fight.fight_date %>
</p>

<p>
  <strong>Fight winner:</strong>
  <%= Player.find(@fight.fight_winner).name %>
</p>

<!--<%= link_to 'Edit', edit_fight_path(@fight) %> |-->
<%= link_to 'Back', fights_path %>